[tool.poetry]
name = "advent of code 2024"
version = "0.1.0"
description = "advent of code 2024 solutions"
authors = ["Lawrence Borst"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "advent of code 2024" }
]


[tool.poetry.scripts]
main = "advent of code 2024.main:main"


[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
